dist: trusty
sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install --requirement requirements.txt

script:
  - py.test tests --cov base62 --durations=10

after_success:
  - coveralls
